-- Script de atualização do banco de produção LiveSun Financeiro
-- Garante que todos os campos necessários estejam presentes, sem apagar dados
-- Execute cada bloco separadamente para evitar erros de campo já existente
-- Faça backup antes de rodar!

-- =============================
-- 1. EMPRESAS
-- =============================
ALTER TABLE empresas 
	ADD COLUMN IF NOT EXISTS nome VARCHAR(150) NOT NULL UNIQUE,
	ADD COLUMN IF NOT EXISTS cnpj VARCHAR(18) UNIQUE,
	ADD COLUMN IF NOT EXISTS criado_em DATETIME DEFAULT CURRENT_TIMESTAMP,
	ADD COLUMN IF NOT EXISTS atualizado_em DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- =============================
-- 2. USERS
-- =============================
ALTER TABLE users 
	ADD COLUMN IF NOT EXISTS empresa_id INT NOT NULL,
	ADD COLUMN IF NOT EXISTS username VARCHAR(80) NOT NULL,
	ADD COLUMN IF NOT EXISTS email VARCHAR(120) NOT NULL,
	ADD COLUMN IF NOT EXISTS password_hash VARCHAR(255) NOT NULL,
	ADD COLUMN IF NOT EXISTS full_name VARCHAR(120),
	ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE,
	ADD COLUMN IF NOT EXISTS is_admin BOOLEAN DEFAULT FALSE,
	ADD COLUMN IF NOT EXISTS dashboard_chart_days INT DEFAULT 30,
	ADD COLUMN IF NOT EXISTS created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	ADD COLUMN IF NOT EXISTS updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- =============================
-- 3. ENTIDADES
-- =============================
ALTER TABLE entidades 
	ADD COLUMN IF NOT EXISTS empresa_id INT NOT NULL,
	ADD COLUMN IF NOT EXISTS nome VARCHAR(150) NOT NULL,
	ADD COLUMN IF NOT EXISTS cnpj_cpf VARCHAR(18) NOT NULL,
	ADD COLUMN IF NOT EXISTS tipo VARCHAR(1),
	ADD COLUMN IF NOT EXISTS fluxo_conta_id INT NULL,
	ADD COLUMN IF NOT EXISTS aliquota_comissao_especifica DECIMAL(5,2),
	ADD COLUMN IF NOT EXISTS valor_repasse DECIMAL(10,2) DEFAULT 0.00,
	ADD COLUMN IF NOT EXISTS vendedor_id INT,
	ADD COLUMN IF NOT EXISTS criado_em DATETIME DEFAULT CURRENT_TIMESTAMP,
	ADD COLUMN IF NOT EXISTS atualizado_em DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	ADD COLUMN IF NOT EXISTS ativo BOOLEAN DEFAULT TRUE;

-- =============================
-- 4. FLUXO_CONTAS_MODELO
-- =============================
ALTER TABLE fluxo_contas_modelo 
	ADD COLUMN IF NOT EXISTS empresa_id INT NOT NULL,
	ADD COLUMN IF NOT EXISTS codigo VARCHAR(20) NOT NULL,
	ADD COLUMN IF NOT EXISTS descricao VARCHAR(200) NOT NULL,
	ADD COLUMN IF NOT EXISTS tipo VARCHAR(1) NOT NULL,
	ADD COLUMN IF NOT EXISTS mascara VARCHAR(50),
	ADD COLUMN IF NOT EXISTS nivel_sintetico INT,
	ADD COLUMN IF NOT EXISTS nivel_analitico INT,
	ADD COLUMN IF NOT EXISTS ativo BOOLEAN DEFAULT TRUE,
	ADD COLUMN IF NOT EXISTS criado_em DATETIME DEFAULT CURRENT_TIMESTAMP,
	ADD COLUMN IF NOT EXISTS atualizado_em DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- =============================
-- 5. CONTAS_BANCO
-- =============================
ALTER TABLE contas_banco 
	ADD COLUMN IF NOT EXISTS empresa_id INT NOT NULL,
	ADD COLUMN IF NOT EXISTS nome VARCHAR(150) NOT NULL,
	ADD COLUMN IF NOT EXISTS banco VARCHAR(50) NOT NULL,
	ADD COLUMN IF NOT EXISTS agencia VARCHAR(10) NOT NULL,
	ADD COLUMN IF NOT EXISTS numero_conta VARCHAR(20) NOT NULL,
	ADD COLUMN IF NOT EXISTS dv VARCHAR(2),
	ADD COLUMN IF NOT EXISTS tipo VARCHAR(20),
	ADD COLUMN IF NOT EXISTS fluxo_conta_id INT,
	ADD COLUMN IF NOT EXISTS saldo_inicial DECIMAL(15,2) DEFAULT 0.00,
	ADD COLUMN IF NOT EXISTS is_principal BOOLEAN NOT NULL DEFAULT 0,
	ADD COLUMN IF NOT EXISTS ativo BOOLEAN DEFAULT TRUE,
	ADD COLUMN IF NOT EXISTS criado_em DATETIME DEFAULT CURRENT_TIMESTAMP;

-- =============================
-- 6. LANCAMENTOS
-- =============================
ALTER TABLE lancamentos 
	ADD COLUMN IF NOT EXISTS empresa_id INT NOT NULL,
	ADD COLUMN IF NOT EXISTS data_evento DATE NOT NULL,
	ADD COLUMN IF NOT EXISTS data_vencimento DATE NOT NULL,
	ADD COLUMN IF NOT EXISTS data_pagamento DATE,
	ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'aberto',
	ADD COLUMN IF NOT EXISTS entidade_id INT NOT NULL,
	ADD COLUMN IF NOT EXISTS fluxo_conta_id INT NOT NULL,
	ADD COLUMN IF NOT EXISTS conta_banco_id INT NOT NULL,
	ADD COLUMN IF NOT EXISTS valor_real DECIMAL(15,2) NOT NULL,
	ADD COLUMN IF NOT EXISTS valor_pago DECIMAL(15,2) DEFAULT 0.00,
	ADD COLUMN IF NOT EXISTS valor_imposto DECIMAL(15,2) DEFAULT 0.00,
	ADD COLUMN IF NOT EXISTS valor_outros_custos DECIMAL(15,2) DEFAULT 0.00,
	ADD COLUMN IF NOT EXISTS numero_documento VARCHAR(50),
	ADD COLUMN IF NOT EXISTS observacoes TEXT,
	ADD COLUMN IF NOT EXISTS criado_em DATETIME DEFAULT CURRENT_TIMESTAMP,
	ADD COLUMN IF NOT EXISTS atualizado_em DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- =============================
-- 7. IMPORTACAO_NFSE
-- =============================
ALTER TABLE importacao_nfse 
	ADD COLUMN IF NOT EXISTS empresa_id INT NOT NULL,
	ADD COLUMN IF NOT EXISTS chave_nota VARCHAR(60) NOT NULL,
	ADD COLUMN IF NOT EXISTS numero_nota VARCHAR(30) NOT NULL,
	ADD COLUMN IF NOT EXISTS data_emissao DATE NOT NULL,
	ADD COLUMN IF NOT EXISTS cnpj_tomador VARCHAR(20) NOT NULL,
	ADD COLUMN IF NOT EXISTS entidade_id INT NULL,
	ADD COLUMN IF NOT EXISTS lancamento_id INT NULL,
	ADD COLUMN IF NOT EXISTS valor_bruto DECIMAL(15,2) NOT NULL,
	ADD COLUMN IF NOT EXISTS valor_impostos DECIMAL(15,2),
	ADD COLUMN IF NOT EXISTS descricao_servico TEXT,
	ADD COLUMN IF NOT EXISTS status_importacao VARCHAR(20) DEFAULT 'sucesso',
	ADD COLUMN IF NOT EXISTS mensagem_erro VARCHAR(255),
	ADD COLUMN IF NOT EXISTS data_importacao DATETIME DEFAULT CURRENT_TIMESTAMP,
	ADD COLUMN IF NOT EXISTS endereco_rua VARCHAR(150),
	ADD COLUMN IF NOT EXISTS endereco_numero VARCHAR(10),
	ADD COLUMN IF NOT EXISTS endereco_bairro VARCHAR(100),
	ADD COLUMN IF NOT EXISTS endereco_cidade VARCHAR(100),
	ADD COLUMN IF NOT EXISTS endereco_uf VARCHAR(2),
	ADD COLUMN IF NOT EXISTS endereco_cep VARCHAR(8),
	ADD COLUMN IF NOT EXISTS telefone VARCHAR(20),
	ADD COLUMN IF NOT EXISTS email VARCHAR(120),
	ADD COLUMN IF NOT EXISTS contrato_produto TEXT,
	ADD COLUMN IF NOT EXISTS aliquota_iss DECIMAL(5,2),
	ADD COLUMN IF NOT EXISTS aliquota_comissao_especifica DECIMAL(5,2),
	ADD COLUMN IF NOT EXISTS valor_repasse DECIMAL(10,2) DEFAULT 0.00,
	ADD COLUMN IF NOT EXISTS vendedor_id INT,
	ADD COLUMN IF NOT EXISTS ativo BOOLEAN DEFAULT TRUE,
	ADD COLUMN IF NOT EXISTS criado_em DATETIME DEFAULT CURRENT_TIMESTAMP,
	ADD COLUMN IF NOT EXISTS atualizado_em DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- =============================
-- 8. PARAMETROS_SISTEMA
-- =============================
ALTER TABLE parametros_sistema 
	ADD COLUMN IF NOT EXISTS empresa_id INT NOT NULL,
	ADD COLUMN IF NOT EXISTS chave VARCHAR(100) NOT NULL,
	ADD COLUMN IF NOT EXISTS valor TEXT NOT NULL,
	ADD COLUMN IF NOT EXISTS tipo VARCHAR(20) DEFAULT 'string',
	ADD COLUMN IF NOT EXISTS descricao VARCHAR(255),
	ADD COLUMN IF NOT EXISTS criado_em DATETIME DEFAULT CURRENT_TIMESTAMP,
	ADD COLUMN IF NOT EXISTS atualizado_em DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

